a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
f = int(input())
g = int(input())
h = int(input())
i = int(input())
newList = [a, b, c, d, e, f, g, h, i]
print(max(newList))
print(newList.index(max(newList))+1)